// words.js

const MASTER_WORD_DATA = [
    // --- GENERAL ARCHAEOLOGY & TOOLS ---
    ["TREASURE", "Valuable items hidden or buried long ago."],
    ["ARTIFACT", "An old object made by people, like a tool or pot."],
    ["EXCAVATE", "To carefully dig up an ancient site."],
    ["FOSSIL", "The remains of an ancient plant or animal."],
    ["RUINS", "What is left of an old building or city."],
    ["SITE", "A location where digging happens."],
    ["TROWEL", "A small hand tool used for careful digging."],
    ["GRID", "The systematic square pattern used for mapping a dig."],
    ["LAYER", "A level of soil that represents a specific time period."],
    ["SHARD", "A broken piece of pottery or glass."],
    ["SCREEN", "Used to sift dirt to find small objects."],
    ["BRUSH", "Used to whisk away dust from a delicate artifact."],
    ["CARBON", "Element used to date how old organic things are."],
    ["DATING", "The method of figuring out how old something is."],
    ["DIG", "What an archaeologist does in the dirt."],
    ["SURVEY", "To look over the land to find where to dig."],
    ["MUSEUM", "Where artifacts are displayed for the public."],
    ["CURATOR", "A person who manages a museum collection."],
    ["HISTORY", "The study of the past."],
    ["ANCIENT", "Something that is very, very old."],
    ["PRESERVE", "To keep something safe from decaying."],
    ["CONTEXT", "The exact position where an object is found."],
    ["STRATA", "Layers of rock or earth."],
    ["TOOL", "An object used to help do work."],
    ["WEAPON", "An object used for hunting or fighting."],
    ["JEWELRY", "Ornaments worn on the body."],
    ["SKELETON", "The framework of bones in a body."],
    ["SKULL", "The bone structure of the head."],
    ["BONES", "What is left of a body after a long time."],
    ["DISCOVERY", "Finding something new or unknown."],
    ["EXPEDITION", "A journey for a specific purpose, like exploration."],
    ["ARCHIVE", "A place where old documents are stored."],
    ["EVIDENCE", "Facts that prove something is true."],
    ["THEORY", "An idea that explains how something happened."],
    ["CULTURE", "The beliefs and customs of a group of people."],
    ["CIVILIZATION", "A complex society with cities and government."],
    ["EMPIRE", "A group of countries ruled by a single leader."],
    ["KINGDOM", "A country ruled by a king or queen."],
    ["TRADE", "Buying, selling, or exchanging goods."],
    ["MERCHANT", "A person who sells goods."],
    ["ROUTE", "A path used for traveling or trading."],
    ["VOYAGE", "A long journey involving travel by sea."],
    ["MARINE", "Related to the sea (underwater archaeology)."],
    ["SHIPWRECK", "The remains of a destroyed ship."],
    ["ANCHOR", "Heavy metal object used to hold a ship in place."],
    ["CARGO", "Goods carried by a ship or vehicle."],

    // --- ANCIENT EGYPT ---
    ["PYRAMID", "Huge triangular tomb for Pharaohs."],
    ["PHARAOH", "A ruler in ancient Egypt."],
    ["MUMMY", "A preserved body wrapped in cloth."],
    ["SPHINX", "Statue with a human head and lion body."],
    ["NILE", "The great river that flows through Egypt."],
    ["DESERT", "A dry, sandy region."],
    ["CAMEL", "Animal used for transport in the desert."],
    ["PAPYRUS", "A plant used to make ancient paper."],
    ["HIEROGLYPH", "A picture used as writing in Egypt."],
    ["SCRIBE", "A person whose job was to write things down."],
    ["TOMB", "A burial place."],
    ["SARCOPHAGUS", "A stone coffin."],
    ["OBELISK", "A tall, four-sided stone pillar."],
    ["SCARAB", "A beetle considered sacred in Egypt."],
    ["ANUBIS", "The jackal-headed god of the dead."],
    ["OSIRIS", "The god of the underworld."],
    ["RA", "The sun god."],
    ["CLEOPATRA", "A famous queen of Egypt."],
    ["RAMSES", "A powerful Pharaoh."],
    ["TUTANKHAMUN", "The 'Boy King' whose tomb was found intact."],
    ["VALLEY", "Low land between hills (Valley of the Kings)."],
    ["TEMPLE", "A building for worship."],
    ["SAND", "Tiny grains of rock found in the desert."],
    ["GOLD", "Precious yellow metal favored by Pharaohs."],
    ["LOTUS", "A water flower common in Egyptian art."],
    ["DELTA", "Where the river splits before reaching the sea."],
    ["FLAIL", "A tool symbolized Pharaoh's power over crops."],
    ["CROOK", "A shepherd's staff, symbol of leadership."],

    // --- ANCIENT GREECE ---
    ["ACROPOLIS", "The 'high city' in Athens."],
    ["PARTHENON", "Famous temple dedicated to Athena."],
    ["ATHENS", "The capital of Greece, birthplace of democracy."],
    ["SPARTA", "Greek city-state known for its warriors."],
    ["ZEUS", "King of the Greek gods."],
    ["HERA", "Queen of the Greek gods."],
    ["POSEIDON", "God of the sea."],
    ["HADES", "God of the underworld."],
    ["ATHENA", "Goddess of wisdom and war."],
    ["APOLLO", "God of the sun and music."],
    ["OLYMPICS", "Athletic games held every four years."],
    ["MYTH", "A traditional story about gods or heroes."],
    ["HOMER", "Poet who wrote the Iliad and Odyssey."],
    ["ODYSSEY", "An epic poem about a long journey."],
    ["TROJAN", "Relating to the city of Troy."],
    ["HORSE", "The wooden animal used to trick Troy."],
    ["PHILOSOPHY", "The study of knowledge and reality."],
    ["SOCRATES", "A famous Greek philosopher."],
    ["PLATO", "Student of Socrates, a philosopher."],
    ["ARISTOTLE", "Student of Plato, a philosopher."],
    ["DEMOCRACY", "Government where people vote."],
    ["CITIZEN", "A recognized subject of a state."],
    ["AGORA", "The public marketplace in Greece."],
    ["THEATER", "Where plays were performed."],
    ["COMEDY", "A funny play."],
    ["TRAGEDY", "A sad or serious play."],
    ["COLUMN", "An upright pillar supporting an arch."],
    ["MARBLE", "Hard limestone used for sculpture."],
    ["STATUE", "A carved or cast figure of a person."],
    ["TRIREME", "An ancient Greek warship."],
    ["SHIELD", "Armor carried on the arm."],
    ["SPEAR", "A weapon with a long shaft and pointed tip."],
    ["HELMET", "Armor for the head."],
    ["OLIVE", "A fruit used to make oil."],
    ["GRAPES", "Fruit used to make wine."],
    ["POTTERY", "Ceramic ware."],
    ["AMPHORA", "A tall jar with two handles."],
    ["MOSAIC", "Art made of small colored stones."],

    // --- ANCIENT ROME ---
    ["ROME", "The capital of the Roman Empire."],
    ["ITALY", "The country where Rome is located."],
    ["TIBER", "The river that runs through Rome."],
    ["LATIN", "The language spoken by Romans."],
    ["FORUM", "The main public square in Rome."],
    ["SENATE", "The governing assembly of Rome."],
    ["CONSUL", "One of the two top officials in the Republic."],
    ["EMPEROR", "The ruler of the Roman Empire."],
    ["CAESAR", "Julius ___, a famous Roman dictator."],
    ["AUGUSTUS", "The first Roman Emperor."],
    ["LEGION", "A large unit of the Roman army."],
    ["SOLDIER", "A person who serves in an army."],
    ["GLADIATOR", "A fighter who entertained the public."],
    ["COLOSSEUM", "A massive amphitheater in Rome."],
    ["ARENA", "Where gladiators fought."],
    ["CHARIOT", "A two-wheeled horse-drawn vehicle."],
    ["RACE", "A competition of speed."],
    ["AQUEDUCT", "A structure to carry water."],
    ["ROAD", "Paved path for travel."],
    ["ARCH", "Curved structure spanning an opening."],
    ["DOME", "A rounded roof."],
    ["CONCRETE", "Building material invented by Romans."],
    ["BATHS", "Public places for washing and socializing."],
    ["TOGA", "A loose outer garment worn by citizens."],
    ["TUNIC", "A simple garment worn by everyone."],
    ["VILLA", "A large country house."],
    ["POMPEII", "City buried by a volcano."],
    ["VESUVIUS", "The volcano that destroyed Pompeii."],
    ["VOLCANO", "A mountain that erupts lava."],
    ["LAVA", "Hot molten rock."],
    ["ASH", "Powder left after a fire or eruption."],
    ["COIN", "Metal money."],
    ["DENARIUS", "A silver Roman coin."],

    // --- ANCIENT CHINA & ASIA ---
    ["CHINA", "Ancient civilization in East Asia."],
    ["DYNASTY", "A line of hereditary rulers."],
    ["EMPEROR", "The supreme ruler of an empire."],
    ["DRAGON", "Mythical creature symbol of power."],
    ["SILK", "Soft fabric made by worms."],
    ["ROAD", "The Silk ___, a trade route."],
    ["WALL", "The Great ___, built for defense."],
    ["RICE", "Staple food crop."],
    ["TEA", "A popular drink from leaves."],
    ["JADE", "A hard, green gemstone."],
    ["BRONZE", "Metal alloy of copper and tin."],
    ["ORACLE", "Bones used to predict the future."],
    ["BAMBOO", "Plant used for building and writing."],
    ["PAPER", "Invented in China for writing."],
    ["INK", "Fluid used for writing."],
    ["COMPASS", "Instrument for finding direction."],
    ["POWDER", "Gun___, an explosive invention."],
    ["CONFUCIUS", "A famous Chinese philosopher."],
    ["BUDDHA", "Founder of Buddhism."],
    ["TEMPLE", "Place of worship (Pagoda)."],
    ["PAGODA", "A tiered tower."],
    ["TERRACOTTA", "Baked clay (Warriors)."],
    ["WARRIOR", "A brave or experienced soldier."],
    ["INDUS", "Valley civilization in ancient India."],
    ["GANGES", "Sacred river in India."],
    ["HIMALAYA", "Mountain range in Asia."],

    // --- MESOPOTAMIA ---
    ["SUMER", "Region in southern Mesopotamia."],
    ["BABYLON", "Famous city in Mesopotamia."],
    ["TIGRIS", "One of the two rivers of Mesopotamia."],
    ["EUPHRATES", "The other river of Mesopotamia."],
    ["FERTILE", "Capable of producing abundant crops."],
    ["CRESCENT", "The ___ Moon shape."],
    ["ZIGGURAT", "A rectangular stepped tower."],
    ["CUNEIFORM", "Wedge-shaped writing on clay tablets."],
    ["TABLET", "A slab of clay used for writing."],
    ["CLAY", "Material used for tablets and bricks."],
    ["HAMMURABI", "King known for his code of laws."],
    ["LAW", "A rule defining correct behavior."],
    ["WHEEL", "Invention for transport."],
    ["PLOW", "Tool for turning soil."],
    ["IRRIGATION", "Watering crops artificially."],
    ["CANAL", "Man-made waterway."],
    ["CITY", "A large human settlement."],
    ["STATE", "A city-___, an independent city."],

    // --- THE AMERICAS (MAYA, AZTEC, INCA) ---
    ["MAYA", "Civilization in Central America."],
    ["AZTEC", "Civilization in Mexico."],
    ["INCA", "Civilization in South America."],
    ["MEXICO", "Modern country, home of Aztecs."],
    ["PERU", "Modern country, home of Incas."],
    ["ANDES", "Mountain range of the Incas."],
    ["JUNGLE", "Thick tropical forest."],
    ["RAINFOREST", "Forest with heavy rainfall."],
    ["CORN", "Maize, a staple crop."],
    ["MAIZE", "Another name for corn."],
    ["BEAN", "Common food crop."],
    ["SQUASH", "Vegetable often grown with corn."],
    ["CHOCOLATE", "Food made from cacao beans."],
    ["CACAO", "Bean used to make chocolate."],
    ["LLAMA", "Pack animal of the Andes."],
    ["ALPACA", "Woolly animal of the Andes."],
    ["FEATHER", "Used for headdresses."],
    ["MASK", "Face covering for ceremonies."],
    ["CALENDAR", "System for organizing time."],
    ["SUN", "Worshipped as a god."],
    ["SACRIFICE", "Offering to a god."],
    ["BALL", "Rubber object used in a game."],
    ["GAME", "Sport played in a stone court."],
    ["MACHU", "___ Picchu, famous Inca city."],
    ["PICCHU", "Machu ___, famous Inca city."],
    ["CUSCO", "Capital of the Inca Empire."],

    // --- STONE AGE & PREHISTORY ---
    ["PALEOLITHIC", "The Old Stone Age."],
    ["NEOLITHIC", "The New Stone Age."],
    ["STONE", "Material for early tools."],
    ["FLINT", "Stone used to start fire."],
    ["FIRE", "Provided warmth and cooked food."],
    ["CAVE", "Natural shelter in rock."],
    ["PAINTING", "Art on cave walls."],
    ["HUNTER", "Person who hunts animals."],
    ["GATHERER", "Person who collects plants."],
    ["NOMAD", "Person who moves from place to place."],
    ["MAMMOTH", "Large extinct hairy elephant."],
    ["SABER", "___-toothed tiger."],
    ["TOOTH", "Part of the mouth."],
    ["CLAW", "Sharp nail of an animal."],
    ["PELT", "Animal skin with fur."],
    ["HIDE", "Animal skin."],
    ["LEATHER", "Treated animal skin."],
    ["AXE", "Chopping tool."],
    ["SPEAR", "Thrusting weapon."],
    ["ARROW", "Projectile shot from a bow."],
    ["BOW", "Weapon for shooting arrows."],
    ["NEEDLE", "Tool for sewing."],
    ["BONE", "Material for needles and tools."],
    ["ANTLER", "Horn of a deer."],
    ["FARMING", "Growing crops."],
    ["AGRICULTURE", "The practice of farming."],
    ["DOMESTIC", "Taming animals for human use."],
    ["DOG", "First domesticated animal."],
    ["SHEEP", "Animal raised for wool."],
    ["GOAT", "Animal raised for milk/meat."],
    ["CATTLE", "Cows and bulls."],
    ["WHEAT", "Grain used for bread."],
    ["BARLEY", "Grain used for food."],

    // --- VIKINGS & MIDDLE AGES (Bonus) ---
    ["VIKING", "Norse explorer and warrior."],
    ["NORSE", "People of the North."],
    ["LONGSHIP", "Viking boat."],
    ["OAR", "Used to row a boat."],
    ["SAIL", "Catches wind to move a boat."],
    ["RAID", "Sudden attack."],
    ["RUNES", "Viking alphabet."],
    ["THOR", "God of thunder."],
    ["ODIN", "God of wisdom and war."],
    ["VALHALLA", "Hall of the slain."],
    ["SWORD", "Weapon with a long blade."],
    ["AXE", "Battle tool."],
    ["CASTLE", "Fortified building."],
    ["KNIGHT", "Armored warrior on horseback."],
    ["ARMOR", "Metal suit for protection."],
    ["KING", "Male ruler."],
    ["QUEEN", "Female ruler."],
    ["CROWN", "Headgear of a ruler."],
    ["THRONE", "Chair of a ruler."],
    ["MOAT", "Water ditch around a castle."],
    ["DRAWBRIDGE", "Bridge that can be raised."],
    ["DUNGEON", "Underground prison."],
    ["TOWER", "Tall structure."],
    ["WALL", "Defensive barrier."],
    ["GATE", "Entrance to a castle."],
    ["SCROLL", "Roll of paper/parchment."],
    ["INK", "Writing fluid."],
    ["QUILL", "Feather pen."],

    // --- GEOGRAPHY & NATURE ---
    ["MAP", "Drawing of an area."],
    ["GLOBE", "Model of the Earth."],
    ["NORTH", "Direction."],
    ["SOUTH", "Direction."],
    ["EAST", "Direction."],
    ["WEST", "Direction."],
    ["OCEAN", "Large body of salt water."],
    ["SEA", "Smaller body of salt water."],
    ["RIVER", "Flowing water."],
    ["LAKE", "Inland body of water."],
    ["MOUNTAIN", "Very high land."],
    ["HILL", "Raised land."],
    ["FOREST", "Land covered with trees."],
    ["PLAIN", "Flat land."],
    ["ISLAND", "Land surrounded by water."],
    ["COAST", "Land next to the sea."],
    ["CLIFF", "Steep rock face."],
    ["CAVE", "Underground hollow."],
    ["ROCK", "Solid mineral material."],
    ["MINERAL", "Natural substance."],
    ["GEM", "Precious stone."],
    ["RUBY", "Red gem."],
    ["EMERALD", "Green gem."],
    ["DIAMOND", "Hardest gem."],
    ["SAPPHIRE", "Blue gem."],
    ["PEARL", "Gem from an oyster."],

    // --- MISC & VERBS ---
    ["SEARCH", "To look for something."],
    ["FIND", "To discover."],
    ["STUDY", "To learn about."],
    ["READ", "To look at words."],
    ["WRITE", "To put words on paper."],
    ["DRAW", "To make a picture."],
    ["MEASURE", "To find size or amount."],
    ["RECORD", "To write down info."],
    ["CLEAN", "To remove dirt."],
    ["FIX", "To repair."],
    ["BUILD", "To construct."],
    ["CREATE", "To make something new."],
    ["PAINT", "To use color."],
    ["CARVE", "To cut into shape."],
    ["TRAVEL", "To go to a new place."],
    ["WALK", "To move on feet."],
    ["RUN", "To move fast."],
    ["CLIMB", "To go up."],
    ["SAIL", "To travel by boat."],
    ["RIDE", "To sit on an animal."],
    ["COOK", "To prepare food."],
    ["EAT", "To consume food."],
    ["SLEEP", "To rest."],
    ["DREAM", "To see images while sleeping."],
    ["THINK", "To use the brain."],
    ["LEARN", "To gain knowledge."]
];